image: node:lts-stretch

stages:
  - build
  - lint

compile:
  stage: build
  before_script:
    - yarn install --dev
  script:
    - yarn global add typescript
    - tsc
  cache:
    paths:
    - build/
    policy: push

eslint:
  stage: lint
  script:
    - yarn global add eslint
    - eslint build/**/*.js
  cache:
    paths:
    - build/
    policy: pull