image: node:latest

stages:
  - build
  - lint

cache:
  paths:
    - node_modules/

install_depend:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

eslint:
  stage: lint
  script:
    - npm install -g eslint
    - eslint --init
    - eslint js/*.js